import javax.swing.*;
import java.net.*;
import java.io.*;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.util.ArrayList;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class AplikasiCekCuacaSederhanaFrame extends javax.swing.JFrame {
private ArrayList<String> daftarFavorit = new ArrayList<>();  // Menyimpan kota favorit
    private DefaultComboBoxModel<String> comboBoxModel;  // Untuk mengelola comboBox

    private String getWeatherData(String city) {
        try {
            String apiKey = "fb2bd2b06926c93515571d299f56a31c"; // Ganti dengan API key Anda
            String urlString = "https://api.openweathermap.org/data/2.5/weather?q=" + city + "&appid=" + apiKey + "&units=metric";
            URL url = new URL(urlString);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");

            BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            return response.toString();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    private String extractJsonValue(String jsonData, String key) {
        int index = jsonData.indexOf(key);
        if (index == -1) return "";
        int startIndex = jsonData.indexOf(":", index) + 1;
        int endIndex = jsonData.indexOf(",", startIndex);
        if (endIndex == -1) endIndex = jsonData.indexOf("}", startIndex);
        return jsonData.substring(startIndex, endIndex).replaceAll("\"", "").trim();
    }
    public AplikasiCekCuacaSederhanaFrame() {
        initComponents();
        comboBoxModel = (DefaultComboBoxModel<String>) comboBoxKota.getModel();  // Mengambil model dari comboBox

    // Menambahkan kota favorit ke ComboBox
    for (String city : daftarFavorit) {
        comboBoxModel.addElement(city);  // Menambahkan kota favorit ke ComboBox
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelUtama = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        textFieldCuaca = new javax.swing.JTextField();
        comboBoxKota = new javax.swing.JComboBox<>();
        buttonCekCuaca = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        labelKota = new javax.swing.JLabel();
        labelCuaca = new javax.swing.JLabel();
        labelGambarCuaca = new javax.swing.JLabel();
        buttonFavorit = new javax.swing.JButton();
        buttonSimpanKeCsv = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCuaca = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelUtama.setBackground(new java.awt.Color(255, 153, 0));

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelJudul.setText("Aplikasi Cek Cuaca Sederhana");

        comboBoxKota.setBackground(new java.awt.Color(255, 204, 153));
        comboBoxKota.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        comboBoxKota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarmasin", "Banjarbaru", "Palangkaraya", "Jakarta", "Sukamara" }));
        comboBoxKota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxKotaItemStateChanged(evt);
            }
        });
        comboBoxKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxKotaActionPerformed(evt);
            }
        });

        buttonCekCuaca.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonCekCuaca.setText("Cek Cuaca");
        buttonCekCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCekCuacaActionPerformed(evt);
            }
        });

        buttonKeluar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        labelKota.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelKota.setText("Pilih Kota");

        labelCuaca.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelCuaca.setText("Menampilan Cuaca");

        labelGambarCuaca.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelGambarCuaca.setText("Kondisi Cuaca");

        buttonFavorit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonFavorit.setText("Tambah favorit");
        buttonFavorit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFavoritActionPerformed(evt);
            }
        });

        buttonSimpanKeCsv.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonSimpanKeCsv.setText("Simpan Ke CSV");
        buttonSimpanKeCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanKeCsvActionPerformed(evt);
            }
        });

        TableCuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableCuaca);

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul)
                .addGap(70, 496, Short.MAX_VALUE))
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelGambarCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelCuaca)
                        .addComponent(labelKota)))
                .addGap(121, 121, 121)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUtamaLayout.createSequentialGroup()
                        .addComponent(comboBoxKota, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCekCuaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUtamaLayout.createSequentialGroup()
                        .addComponent(textFieldCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFavorit))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSimpanKeCsv)
                            .addComponent(buttonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUtamaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(labelJudul)
                .addGap(43, 43, 43)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxKota, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCekCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCuaca)
                    .addComponent(textFieldCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(labelGambarCuaca))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelUtamaLayout.createSequentialGroup()
                                .addComponent(buttonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSimpanKeCsv, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCekCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCekCuacaActionPerformed
    String city = comboBoxKota.getSelectedItem().toString();
    String jsonData = getWeatherData(city);

    if (jsonData != null) {
        try {
            // Debugging: tampilkan data JSON yang diterima
            System.out.println("Data JSON: " + jsonData);

            // Mengambil suhu dari data JSON
            String temperature = extractJsonValue(jsonData, "\"temp\":");
            textFieldCuaca.setText(temperature + "°C");

            // Mengambil ikon cuaca dari data JSON
            String weatherIcon = extractJsonValue(jsonData, "\"icon\":\"");
            System.out.println("Icon cuaca: " + weatherIcon); // Debugging

            // Hapus karakter yang tidak perlu jika ada
            if (weatherIcon.endsWith("}]")) {
                weatherIcon = weatherIcon.substring(0, weatherIcon.length() - 2);
            }

            // Tentukan URL gambar berdasarkan ikon cuaca
            String imageUrl = "";
            switch (weatherIcon) {
                case "01d":
                    imageUrl = "http://openweathermap.org/img/wn/01d@2x.png"; // Cerah (Siang)
                    break;
                case "01n":
                    imageUrl = "http://openweathermap.org/img/wn/01n@2x.png"; // Cerah (Malam)
                    break;
                case "02d":
                case "02n":
                case "03d":
                case "03n":
                    imageUrl = "http://openweathermap.org/img/wn/03d@2x.png"; // Berawan
                    break;
                case "09d":
                case "09n":
                case "10d":
                case "10n":
                    imageUrl = "http://openweathermap.org/img/wn/09d@2x.png"; // Hujan
                    break;
                case "13d":
                case "13n":
                    imageUrl = "http://openweathermap.org/img/wn/13d@2x.png"; // Salju
                    break;
                case "50d":
                case "50n":
                    imageUrl = "http://openweathermap.org/img/wn/50d@2x.png"; // Kabut
                    break;
                default:
                    imageUrl = "http://openweathermap.org/img/wn/01d@2x.png"; // Default (Cerah)
                    break;
            }

            System.out.println("URL Gambar: " + imageUrl); // Debugging

            // Mengunduh gambar cuaca
            try {
                URL url = new URL(imageUrl);
                Image img = ImageIO.read(url); // Mengunduh gambar cuaca
                ImageIcon icon = new ImageIcon(img);
                labelGambarCuaca.setIcon(icon); // Menampilkan gambar di JLabel
                labelGambarCuaca.setText(""); // Hapus teks jika ada gambar yang ditampilkan
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Gagal mengunduh gambar cuaca", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal mengambil data cuaca", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        textFieldCuaca.setText("Data cuaca tidak ditemukan.");
        labelGambarCuaca.setIcon(null); // Hapus gambar jika data tidak ditemukan
        labelGambarCuaca.setText("Gambar tidak tersedia"); // Menampilkan pesan jika gambar tidak ada
    }
    }//GEN-LAST:event_buttonCekCuacaActionPerformed

    private void comboBoxKotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxKotaItemStateChanged
        // Bisa digunakan untuk event saat memilih kota, jika perlu.
    // Misalnya, update teks atau elemen lain jika diperlukan.
    }//GEN-LAST:event_comboBoxKotaItemStateChanged

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
         System.exit(0); // Menutup aplikasi
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void comboBoxKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxKotaActionPerformed
        
    }//GEN-LAST:event_comboBoxKotaActionPerformed

    private void buttonFavoritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFavoritActionPerformed
        // Ambil kota yang dipilih
    String selectedCity = comboBoxKota.getSelectedItem().toString();

    // Cek apakah kota sudah ada di daftar favorit
    if (!daftarFavorit.contains(selectedCity)) {
        // Menambahkan kota ke daftar favorit
        daftarFavorit.add(selectedCity);
        
        // Menambahkan kota favorit ke ComboBox (jika belum ada)
        comboBoxModel.addElement(selectedCity);  // comboBoxModel adalah model ComboBox
        JOptionPane.showMessageDialog(this, "Kota ditambahkan ke favorit!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Kota sudah ada di favorit!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_buttonFavoritActionPerformed

    private void buttonSimpanKeCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanKeCsvActionPerformed
        String city = comboBoxKota.getSelectedItem().toString(); // Ambil kota yang dipilih
    String temperature = textFieldCuaca.getText(); // Ambil suhu yang ditampilkan
    
    // Periksa apakah data cuaca sudah ada
    if (temperature.isEmpty() || temperature.equals("Data cuaca tidak ditemukan.")) {
        JOptionPane.showMessageDialog(this, "Data cuaca belum tersedia. Cek cuaca terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Tentukan nama file CSV
    String fileName = "data_cuaca.csv";
    
    // Menulis ke file CSV
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName, true))) { // true untuk append
        // Format data yang akan disimpan: Kota, Suhu
        writer.write(city + "," + temperature);
        writer.newLine(); // Pindah ke baris berikutnya
        JOptionPane.showMessageDialog(this, "Data cuaca berhasil disimpan ke " + fileName, "Sukses", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data cuaca.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_buttonSimpanKeCsvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhanaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhanaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhanaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhanaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiCekCuacaSederhanaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCuaca;
    private javax.swing.JButton buttonCekCuaca;
    private javax.swing.JButton buttonFavorit;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonSimpanKeCsv;
    private javax.swing.JComboBox<String> comboBoxKota;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCuaca;
    private javax.swing.JLabel labelGambarCuaca;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelKota;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTextField textFieldCuaca;
    // End of variables declaration//GEN-END:variables

}